const ngDirectives = [
    ["app", "ng-app"],
    ["bind", "ng-bind"],
    ["innerHTML", "ng-bind-html"],
    ["bindTemplate", "ng-bind-template"],
    ["checked", "ng-checked"],
    ["ngClass", "ng-class"],
    ["ngClassEven", "ng-class-even"],
    ["ngClassOdd", "ng-class-odd"],
    ["ngCloak", "ng-clock"],
    // ["controller", "ng-controller"],
    // ["ngCsp", "ng-csp"],
    ["disabled", "ng-disabled"],
    // ["ngForm", "ng-form"],
    ["href", "ng-href"],
    ["ngInclude", "ng-include"],
    // ["ngInit", ""],
    ["ngJq", "ng-jq"],
    // ["ngList", ""],
    ["maxlength", "ng-maxlength"],
    ["minlength", "ng-minlength"],
    // ["ngModelOptions", ""],
    // ["ngNonBindable", "ng-non-bindable"],
    ["open", "ng-open"],
    // ["ngOptions", ""],
    // ["ngPattern", ""],
    // ["ngPlural", "ng-pluralize "],
    ["readonly", "ng-readonly"],
    ["required", "ng-required"],
    ["selected", "ng-selected"],
    ["src", "ng-src"],
    ["srcset", "ng-srcset"],
    ["ngStyle", "ng-style"],
    ["ngContent", "ng-transclude"],
    ["value", "ng-value"],
];

const ngEvents = [
    ["blur", "ng-blur"],
    ["change", "ng-change"],
    ["click", "ng-click"],
    ["copy", "ng-copy"],
    ["focus", "ng-focus"],
    ["cut", "ng-cut"],
    ["dblclick", "ng-dblclick"],
    ["mousedown", "ng-mousedown"],
    ["mouseenter", "ng-mouseenter"],
    ["mouseleave", "ng-mouseleave"],
    ["mousemove", "ng-mousemove"],
    ["mouseover", "ng-mouseover"],
    ["mouseup", "ng-mouseup"],
    ["keydown", "ng-keydown"],
    ["keypress", "ng-keypress"],
    ["keyup", "ng-keyup"],
    ["paste", "ng-paste"], ,
    ["ngSubmit", "ng-submit"],
];

const ngSpecial = [
    // ["ngRepeat", ""],
    ["\\*ngHide", "ng-hide"],
    ["\\*ngIf", "ng-if"],
    ["\\*ngShow", "ng-show"],
    ["\\*ngSwitch", "ng-switch"],
    ["[(ngModel)]", "ng-model"],
];

module.exports = {
    directives: ngDirectives,
    events: ngEvents,
    special: ngSpecial,
};